@startuml sd-systemDiagram
mainframe **sd** Music-Light System

actor User
participant "UI" as GPIO
participant "RPI Client" as Client
participant "RPI Server" as Server
participant "DAC" as Sound
participant "Speaker" as Speaker
participant "LED Matrix" as LED

User ->> GPIO : Press "Play/Pause"
activate GPIO
GPIO ->> Client : "Play/Pause" pressed
deactivate GPIO

activate Client

loop For each song in playlist
    par Audio Output
        Client ->> Sound : Play song
        activate Sound
        Sound ->> Speaker : Play song
        deactivate Sound
    else Visualizer
        Client ->> LED : Start LED
    end

    alt Song is playing
        note right of Client
              Refer "Song is playing" sequence diagram
        end note
    else Song is paused
        note right of Client
              Refer "Song is paused" sequence diagram
        end note
    end

    note right of Client 
            Song finishes playing
    end note
    Client -> Server : Request next song
    activate Server
    Server --> Client : Send next song
    deactivate Server

    Client -> Client : Perform DSP on audio
    
end

deactivate Client

hide footbox

@enduml
