@startuml sd-song_playing
mainframe **sd** Music-Light System: [alt] Song is playing

actor User
participant "UI" as GPIO
participant "RPI Client" as Client
participant "RPI Server" as Server
participant "DAC" as Sound
participant "Speaker" as Speaker
participant "LED Matrix" as LED

opt Volume Up
    User ->> GPIO : Press "Volume +"
    activate GPIO
    GPIO ->> Client : "Volume +" pressed
    deactivate GPIO
    Client++
    Client ->> Sound : Volume up
    Client--
    activate Sound
    Sound ->> Speaker : Volume up
    deactivate Sound
end

opt Volume Down
    User ->> GPIO : Press "Volume -"
    activate GPIO
    GPIO ->> Client : "Volume -" pressed
    deactivate GPIO
    Client++
    Client ->> Sound : Volume down
    Client--
    activate Sound
    Sound ->> Speaker : Volume down
    deactivate Sound
end

opt Pause song
    User ->> GPIO : Press "Play/Pause"
    activate GPIO
    GPIO ->> Client : "Play/Pause" pressed
    deactivate GPIO
    Client++
    Client ->> Sound : Pause song
    activate Sound
    Sound ->> Speaker : Pause song
    deactivate Sound
    Client ->> LED : Pause LED
    Client--
end
opt Skip song
    User ->> GPIO : Press "Skip"
    activate GPIO
    GPIO ->> Client : "Skip" pressed
    deactivate GPIO
    Client++
    Client -> Client : Play next song
    Client -> Server : Request next song
    activate Server
    Server --> Client : Send next song
    deactivate Server
    Client ->> Sound : Play song
    activate Sound
    Sound ->> Speaker : Play song
    deactivate Sound
    Client ->> LED : Start LED
    Client--
end
opt Rewind song
    User ->> GPIO : Press "Rewind"
    activate GPIO
    GPIO ->> Client : "Rewind" pressed
    deactivate GPIO
    Client++
    Client -> Client : Play previous song
    Client -> Server : Request previous song
    activate Server
    Server --> Client : Send previous song
    deactivate Server
    Client ->> Sound : Play song
    activate Sound
    Sound ->> Speaker : Play song
    deactivate Sound
    Client ->> LED : Start LED
    Client--
end
opt Shuffle
    User ->> GPIO : Press "Shuffle"
    activate GPIO
    GPIO ->> Client : "Shuffle" pressed
    deactivate GPIO
    Client++
    Client -> Server : Shuffle playlist
    activate Server
    Server -> Server : Shuffle playlist
    Server -->> Client : New shuffled songs
    deactivate Server
    Client--
end

deactivate Client

hide footbox

@enduml
